CREATE DATABASE unitest;

CREATE TABLE IF NOT EXISTS usuarios(
    id_usuario integer UNIQUE AUTO_INCREMENT,
    nombre varchar(40) not null,
    primer_apellido varchar(40) not null,
    segundo_apellido varchar(40),
    edad integer not null,
    genero varchar(15) not null,
    email varchar(60) not null PRIMARY KEY,
    password varchar(100) not null
);

CREATE TABLE IF NOT EXISTS test(
    id_test INTEGER PRIMARY KEY AUTO_INCREMENT,
    pregunta1 INTEGER,
    pregunta2 INTEGER,
    pregunta3 INTEGER,
    pregunta4 INTEGER,
    pregunta5 INTEGER,
    pregunta6 INTEGER,
    pregunta7 INTEGER,
    pregunta8 INTEGER,
    pregunta9 INTEGER,
    pregunta10 INTEGER,
    pregunta11 INTEGER,
    pregunta12 INTEGER,
    pregunta13 INTEGER,
    pregunta14 INTEGER,
    pregunta15 INTEGER,
    pregunta16 INTEGER,
    pregunta17 INTEGER,
    pregunta18 INTEGER,
    pregunta19 INTEGER,
    pregunta20 INTEGER,
    pregunta21 INTEGER,
    pregunta22 INTEGER,
    pregunta23 INTEGER,
    pregunta24 INTEGER,
    pregunta25 INTEGER,
    pregunta26 INTEGER,
    pregunta27 INTEGER,
    pregunta28 INTEGER,
    pregunta29 INTEGER,
    pregunta30 INTEGER,
    pregunta31 INTEGER,
    pregunta32 INTEGER,
    pregunta33 INTEGER,
    pregunta34 INTEGER,
    pregunta35 INTEGER,
    pregunta36 INTEGER,
    pregunta37 INTEGER,
    pregunta38 INTEGER,
    pregunta39 INTEGER,
    pregunta40 INTEGER,
    pregunta41 INTEGER,
    pregunta42 INTEGER,
    pregunta43 INTEGER,
    pregunta44 INTEGER,
    pregunta45 INTEGER,
    pregunta46 INTEGER,
    pregunta47 INTEGER,
    pregunta48 INTEGER,
    pregunta49 INTEGER,
    pregunta50 INTEGER,
    pregunta51 INTEGER,
    pregunta52 INTEGER,
    pregunta53 INTEGER,
    pregunta54 INTEGER,
    pregunta55 INTEGER,
    pregunta56 INTEGER,
    pregunta57 INTEGER,
    pregunta58 INTEGER,
    pregunta59 INTEGER,
    pregunta60 INTEGER,
    pregunta61 INTEGER,
    pregunta62 INTEGER,
    pregunta63 INTEGER,
    pregunta64 INTEGER,
    pregunta65 INTEGER,
    pregunta66 INTEGER,
    pregunta67 INTEGER,
    pregunta68 INTEGER,
    pregunta69 INTEGER,
    pregunta70 INTEGER,
    pregunta71 INTEGER,
    pregunta72 INTEGER,
    pregunta73 INTEGER,
    pregunta74 INTEGER,
    pregunta75 INTEGER,
    pregunta76 INTEGER,
    pregunta77 INTEGER,
    pregunta78 INTEGER,
    pregunta79 INTEGER,
    pregunta80 INTEGER,
    pregunta81 INTEGER,
    pregunta82 INTEGER,
    pregunta83 INTEGER,
    pregunta84 INTEGER,
    pregunta85 INTEGER,
    pregunta86 INTEGER,
    pregunta87 INTEGER,
    pregunta88 INTEGER,
    pregunta89 INTEGER,
    pregunta90 INTEGER,
    pregunta91 INTEGER,
    pregunta92 INTEGER,
    pregunta93 INTEGER,
    pregunta94 INTEGER,
    pregunta95 INTEGER,
    pregunta96 INTEGER,
    pregunta97 INTEGER,
    pregunta98 INTEGER,
    c integer AS (pregunta1+pregunta12+pregunta20+pregunta53+pregunta64+pregunta71+pregunta78+pregunta85+pregunta91+pregunta98+pregunta2+pregunta15+pregunta46+pregunta51),
    h integer AS (pregunta9+pregunta25+pregunta34+pregunta41+pregunta56+pregunta67+pregunta74+pregunta80+pregunta89+pregunta95+pregunta30+pregunta63+pregunta72+pregunta86),
    a integer AS (pregunta3+pregunta11+pregunta21+pregunta28+pregunta36+pregunta45+pregunta50+pregunta57+pregunta81+pregunta96+pregunta22+pregunta39+pregunta76+pregunta82),
    s integer AS (pregunta8+pregunta16+pregunta23+pregunta33+pregunta44+pregunta52+pregunta62+pregunta70+pregunta87+pregunta92+pregunta4+pregunta29+pregunta40+pregunta69),
    i integer AS (pregunta6+pregunta19+pregunta27+pregunta38+pregunta47+pregunta54+pregunta60+pregunta75+pregunta83+pregunta97+pregunta10+pregunta26+pregunta59+pregunta90),
    d integer AS (pregunta5+pregunta14+pregunta24+pregunta31+pregunta37+pregunta48+pregunta58+pregunta65+pregunta73+pregunta84+pregunta13+pregunta18+pregunta43+pregunta66),
    e integer AS (pregunta17+pregunta32+pregunta35+pregunta42+pregunta49+pregunta61+pregunta68+pregunta77+pregunta88+pregunta93+pregunta7+pregunta55+pregunta79+pregunta94)
);